### ISSUE TITLE
Panic inside PGX function does not print the stack trace

### ISSUE THREAD

**Issue by askiada** [arsham/dbtools#1]
PGX function is recovering from panics and using multierror package to group the errors into one. However, it makes difficult to track exactly where the panic happened.
I wrote a non-elegant snippet to handle it and print the stack trace of each error.

```
type StackTracer interface {
	StackTrace() errors.StackTrace
}

func printStackTrace(err error) error {
	errTmp := err
	for {
		errTmp = errors.Unwrap(errTmp)
		if errTmp == nil {
			break
		}
		if errTmp, ok := errTmp.(StackTracer); ok {
			for _, f := range errTmp.StackTrace() {
				fmt.Printf("%+s:%d\n", f, f)
			}
		}
	}
	return err
}


func DoSomething() error {
	return errors.New("blablabla")
}


//...
err := db.PGX(ctx, func(tx pgx.Tx) error {
	return DoSomething()
})
if err != nil {
	return errors.Wrap(printStackTrace(err), "something went wrong")
}
//...
```

Could it be possible to handle it from this package? Or maybe to have an option to print stack traces

**Comment by arsham** [comment]
Fixed in 93f13ca935a9a986c47c6dd0e8877e96bf65a32a
